### PR TITLE
User can finish todo item and clear them.

### PR DESCRIPTION
**Pull request by chunyenHuang**

### CODE REVIEW

**Comment by zanedefazio** [comment]
Merge master into this branch
`git checkout master`
`git pull`
`git checkout delete-todo`
`git merge master`
`git status`
`git push origin delete-todo`

**Comment by chunyenHuang** [comment]
```
todo $ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
todo $ git pull
Already up-to-date.
todo $ git checkout delete-todo
Switched to branch 'delete-todo'
todo $ git merge master
Already up-to-date.
todo $ git status
On branch delete-todo
nothing to commit, working directory clean
todo $ git push origin delete-todo
Everything up-to-date
```

But It doesnt merge to master ...

**Comment by chunyenHuang** [comment]
or have to do the opposite?

```
git checkout master
git merge --no-ff delete-todo
git push origin master
```

**Comment by zanedefazio** [comment]
Ok, I just wanted to make sure your branch had master's changes.  Is this your final commit for this pull request?

**Comment by chunyenHuang** [comment]
yes~~

**Pull request merged**
